version: '3.8'

services:
  eureka-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - spring-net
    volumes:
      - maven-cache:/root/.m2
    command:
      - java
      - -jar
      - app.jar
      - --server.address=0.0.0.0

  api-gateway:
    build:
      context: ./api-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - spring-net
    volumes:
      - maven-cache:/root/.m2
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    command:
      - java
      - -jar
      - app.jar
      - --server.address=0.0.0.0

volumes:
  maven-cache:

networks:
  spring-net:
