server:
  port: 8081

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-5iwb.onrender.com/eureka/
  instance:
    preferIpAddress: false
    hostname: user.sameerbiradar.xyz
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 443
    statusPageUrl: https://user.sameerbiradar.xyz/actuator/info
    healthCheckUrl: https://user.sameerbiradar.xyz/actuator/health
    homePageUrl: https://user.sameerbiradar.xyz


