server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
              filters:
                - RewritePath=/user/(?<remaining>.*), /${remaining}
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-5iwb.onrender.com/eureka/
    register-with-eureka: true
    fetch-registry: true

# Optional but helpful
  instance:
    hostname: api-gateway-service-myx7.onrender.com
    prefer-ip-address: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
