server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
              filters:
                - RewritePath=/user/(?<remaining>.*), /${remaining}
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://eureka.sameerbiradar.xyz/eureka/
      register-with-eureka: true
      fetch-registry: true

# Optional but helpful
  instance:
    prefer-ip-address: true
#    ip-address: ${CLOUD_PUBLIC_IP}  # Optional, set this only if you're injecting an external IP
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
