name: Build & Deploy Spring Boot Microservices

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build Discovery Server
        working-directory: discovery-server
        run: mvn clean package -DskipTests

      - name: Build API Gateway
        working-directory: api-gateway-service
        run: mvn clean package -DskipTests

      # Optional: Deploy to Render via Webhook or API if needed
      # You can use curl to call Render deploy hook (see below)
